name: 'Transformations Counseling Group, LCSW'
favicon: null
layout_spectrum: 1
typography_spectrum: 0.7447
title: 'Transformations Counseling Group, LCSW'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c0e9bc'
    - '#10ac06'
    - '#000000'
    - '#55bce5'
    - '#3b6e36'
  brandStrength: 0.4814786349888891
  lightness: 0.3125
  saturation: 0.25
  rhythmicContrast: 0.7079037413932383
purpose: []
